spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://postgres:5432/iam_db}
    username: ${DB_USERNAME:iam_user}
    password: ${DB_PASSWORD:iam_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
      continue-on-error: true

management:
  health:
    redis:
      enabled: true
