spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/iam_db}
    username: ${DB_USERNAME:iam_user}
    password: ${DB_PASSWORD:iam_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
  sql:
    init:
      mode: never

management:
  health:
    redis:
      enabled: true

logging:
  level:
    root: WARN
