spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/iam_db
    username: iam_user
    password: iam_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
      continue-on-error: true

management:
  health:
    redis:
      enabled: false